Repository openshift/cincinnati-graph-data, pull requests merged in 2020-01, with the labels that each got.

#5 Add blocked-edges for 4.2.11
  blocked-edges/4.2.11-s390x.yaml
  blocked-edges/4.2.11.yaml
Labels: size/XS

#6 Update readme
  README.md
Labels: size/M

#7 README: Link from workflow list to Quay-label section
  README.md
Labels: size/XS

#8 channels: promote 4.1.29 and 4.2.13
  channels/candidate-4.2.yaml
  channels/prerelease-4.1.yaml
Labels: size/XS

#9 Revert "Process versions in semver order"
  hack/graph-util.py
Labels: size/XS

#10 Fix python format after semver revert
  hack/graph-util.py
Labels: size/XS

#11 Make the calls to sync multithreaded
  hack/graph-util.py
Labels: size/S

#12 channels: promote 4.1.29 and 4.2.13
  channels/fast-4.2.yaml
  channels/stable-4.1.yaml
  channels/stable-4.2.yaml
Labels: size/XS

#13 channels/candidate-4.3: Promote 4.3.0-rc.0-x86_64
  blocked-edges/4.3.0-rc.0.yaml
  channels/candidate-4.3.yaml
Labels: size/XS

#15 prerelease-4.1: add 4.1.30
  channels/prerelease-4.1.yaml
Labels: lgtm, size/XS

#17 Block 3.2.13-s390x incoming edges: https://bugzilla.redhat.com/1789260
  blocked-edges/4.2.13-s390x.yaml
Labels: size/XS

#16 hack/graph-util: Handle architecture build metadata
  README.md
  hack/graph-util.py
Labels: size/L

#14 add 4.2.14 in candidate-4.2
  channels/candidate-4.2.yaml
Labels: size/XS

#19 Adding LalatenduMohanty as cincinnati-graph-data-approvers
  OWNERS_ALIASES
Labels: size/XS

#18 Add 4.2.14 to stable
  channels/fast-4.2.yaml
Labels: size/XS

#20 Use the right format for specifying "only x86_64"
  channels/fast-4.2.yaml
Labels: size/XS

#21 channels/fast-4.2: Promote 4.1.30
  channels/fast-4.2.yaml
Labels: size/XS

#22 channels/stable: 4.1.30 and 4.2.14 (amd64) to stable
  channels/stable-4.1.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#25 Read Quay token from file as well as from command line
  hack/graph-util.py
Labels: approved, lgtm, size/S

#28 Add rc3 to candidate-4.3
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#29 candidate-4.2: add 4.2.16 and 4.1.31
  channels/candidate-4.2.yaml
Labels: approved, lgtm, size/XS

#27 channels/prerelease-4.1: Promote 4.1.31
  channels/prerelease-4.1.yaml
Labels: approved, lgtm, size/XS

#31 candidate-4.3: add 4.3.0
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#33 channels/*-4.2: Explain why we skipped 4.2.15
  channels/candidate-4.2.yaml
  channels/fast-4.2.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#32 Blocking all the edges to 4.3.0 because of bz 1793635
  blocked-edges/4.3.0.yaml
Labels: approved, lgtm, size/XS

#34 Blocking edges to candidate 4.3.0-rc.3
  blocked-edges/4.3.0-rc.3.yaml
Labels: approved, lgtm, size/XS

#35 Adding 4.3.0 GA bits to fast channel
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#36 Adding 4.3.0 GA bits to stable channel
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#37 add 4.2.16 to fast
  channels/fast-4.2.yaml
Labels: approved, lgtm, size/XS

#38 stable-4.2: add 4.2.16
  channels/fast-4.2.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#39 stable-4.1: add 4.1.31
  channels/stable-4.1.yaml
Labels: approved, lgtm, size/XS
