Repository openshift/cincinnati-graph-data, pull requests merged in 2020-02, with the labels that each got.

#40 Enable the 4.2.16 to 4.3.0 upgrade
  blocked-edges/4.3.0.yaml
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#41 Do not add 4.2 s390 release to 4.3 channels
  channels/fast-4.3.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#43 candidate-4.3: add 4.3.1
  blocked-edges/4.3.1.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#46 blocked-edges/OWNERS: Only release-admins can approve
  blocked-edges/OWNERS
Labels: approved, lgtm, size/S

#45 channels/candidate-4.3: Promote 4.2.16+amd64
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#44 blocked-edges/4.3.0-rc.3: Allow 4.3.0-rc.0 -> 4.3.0-rc.3
  blocked-edges/4.3.0-rc.0.yaml
  blocked-edges/4.3.0-rc.3.yaml
Labels: approved, lgtm, size/XS

#42 Print the architecture in log messages
  hack/graph-util.py
Labels: approved, lgtm, size/M

#49 candidate-4.2: add 4.2.18
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#50 candidate-4.1: add 4.1.34
  channels/candidate-4.2.yaml
  channels/prerelease-4.1.yaml
Labels: approved, lgtm, size/XS

#51 candidate-4.3: add 4.3.2
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#53 fast-4.3: add 4.3.1
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#54 candidate-4.2: add 4.2.19
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#52 stable-4.3: add 4.3.1
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#48 Return a better error if you forget to add the subcommand
  hack/graph-util.py
Labels: approved, lgtm, size/XS

#58 README: Link to docs for channel semantics
  README.md
Labels: approved, lgtm, size/XS

#62 channels: Explain why we skipped 4.1.32 and 4.1.33
  channels/candidate-4.2.yaml
  channels/fast-4.2.yaml
  channels/prerelease-4.1.yaml
  channels/stable-4.1.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/S

#61 channels: Explain why we skipped 4.2.17
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
  channels/fast-4.2.yaml
  channels/fast-4.3.yaml
  channels/stable-4.2.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/S

#63 channels: Explain the lack of 4.2.3, 4.2.5, and 4.2.6
  channels/candidate-4.2.yaml
  channels/fast-4.2.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#56 candidate-4.2: add 4.2.20
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#73 channels: Add 4.2.16+amd64 back to candidate-4.3 and fast-4.3
  channels/candidate-4.3.yaml
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#64 channels/fast-4.2: Promote 4.2.19 (and 4.2.19+amd64 to fast-4.3)
  channels/fast-4.2.yaml
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#74 raw/metadata.json: add historical metadata from quay
  raw/OWNERS
  raw/metadata.json
Labels: approved, lgtm, size/S

#65 channels/stable-4.2: 4.2.18 to stable
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#76 channels/fast-4.2: Promote 4.1.34 to fast-4.2
  channels/fast-4.2.yaml
Labels: approved, lgtm, size/XS

#57 candidate-4.3: add 4.3.3
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#66 channels/stable-4.2: 4.2.19 to stable
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#68 channels/stable-4.2: 4.2.20 to stable
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#85 channels/fast-4.2: Promote 4.2.20
  channels/fast-4.2.yaml
Labels: approved, lgtm, size/XS

#86 channels/fast-4.3: Promote 4.2.20+amd64
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS
