Repository openshift/cincinnati-graph-data, pull requests merged in 2020-03, with the labels that each got.

#87 Adding information why 4.3.2 and 4.3.3 is not in fast,stable 4.3
  channels/fast-4.3.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#81 candidate-4.2: add 4.2.21
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#98 Adding 4.1.37 to candidate-4.2
  channels/candidate-4.2.yaml
Labels: approved, lgtm, size/XS

#91 prerelease-4.1: add 4.1.37
  channels/prerelease-4.1.yaml
Labels: approved, lgtm, size/XS

#88 Adding information about 4.3.4
  channels/candidate-4.3.yaml
  channels/fast-4.3.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#99 candidate-4.3: Add 4.3.5
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#89 candidate-4.2: add 4.2.22
  channels/candidate-4.2.yaml
Labels: approved, lgtm, size/XS

#90 candidate-4.3: add 4.2.22
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#100 Added 4.3.2->4.3.3 to channels
  blocked-edges/4.3.2.yaml
  blocked-edges/4.3.3.yaml
  channels/fast-4.3.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/S

#101 Adding 4.3.5 to fast-4.3 channel
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#105 Adding information why 4.3.6 is not in candidate,fast 4.3
  channels/candidate-4.3.yaml
  channels/fast-4.3.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#103 Add 4.2.21 to fast channels
  channels/fast-4.2.yaml
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#107 Add 4.2.22 to fast channel
  channels/fast-4.2.yaml
  channels/fast-4.3.yaml
Labels: approved, lgtm, size/XS

#108 Add 4.1.34 to stable-4.1, stable-4.2
  channels/fast-4.2.yaml
  channels/stable-4.1.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm, size/XS

#106 Add 4.2.21 to stable-4.2
  channels/stable-4.2.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#110 Add 4.1.38 to candidate
  channels/candidate-4.2.yaml
  channels/prerelease-4.1.yaml
Labels: approved, lgtm, size/XS

#102 Adding 4.3.5 to stable-4.3 channel
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#109 Add 4.2 edges into stable-4.3
  channels/stable-4.3.yaml
Labels: approved, lgtm, size/XS

#111 channels: Add candidate-4.4, fast-4.4, and stable-4.4
  channels/candidate-4.4.yaml
  channels/fast-4.4.yaml
  channels/stable-4.4.yaml
Labels: approved, lgtm, size/XS

#114 channels/candidate-4.4: Add 4.4.0-rc.0 and its update source 4.3.5
  channels/candidate-4.4.yaml
Labels: approved, lgtm, size/XS

#113 channels: Add candidate-4.5, fast-4.5, and stable-4.5
  channels/candidate-4.5.yaml
  channels/fast-4.5.yaml
  channels/stable-4.5.yaml
Labels: approved, lgtm, size/XS

#115 Add 4.2.23 to candidate
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm, size/XS

#117 Add 4.2.22 to stable
  channels/stable-4.2.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm

#125 Block upgrades to 4.3.5 and 4.2.22
  blocked-edges/4.2.22.yaml
  blocked-edges/4.3.5.yaml
Labels: approved, lgtm

#130 Add 4.2.25 to candidate
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm

#129 add 4.4.0-rc.2 to candidate
  channels/candidate-4.4.yaml
Labels: approved, lgtm

#133 Adding 4.3.8 to candidate
  channels/candidate-4.3.yaml
  channels/candidate-4.4.yaml
Labels: approved, lgtm

#134 Add logging verbosity
  hack/graph-util.py
Labels: approved, lgtm

#135 Switch logging level to 'info' by default
  hack/graph-util.py
Labels: approved, lgtm

#131 Add 4.2.25 to fast
  channels/fast-4.2.yaml
  channels/fast-4.3.yaml
Labels: approved, lgtm

#120 channels/stable-4.1: Promote 4.1.38 to stable-4.1 and fast-4.2
  channels/fast-4.2.yaml
  channels/stable-4.1.yaml
  channels/stable-4.2.yaml
Labels: approved, lgtm

#137 add 4.4.0-rc.4 to candidate
  channels/candidate-4.4.yaml
Labels: approved, lgtm

#136 blocked-edges/4.3: Block all 4.2->4.3 on PodIP vs. PodIPs, bug 1816302
  blocked-edges/4.3.0.yaml
  blocked-edges/4.3.2.yaml
  blocked-edges/4.3.3.yaml
  blocked-edges/4.3.5.yaml
  blocked-edges/4.3.8.yaml
Labels: approved, lgtm

#138 Adding 4.3.8 to fast channel
  channels/fast-4.3.yaml
Labels: approved, lgtm

#132 Add 4.2.25 to stable
  channels/stable-4.2.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm

#139 Adding 4.3.8 to stable channel
  channels/stable-4.3.yaml
Labels: approved, lgtm

#141 Add 4.2.26 to candidate
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
Labels: approved, lgtm

#140 Add 4.3.9 to candidate
  channels/candidate-4.3.yaml
  channels/candidate-4.4.yaml
Labels: approved, lgtm

#147 channels/stable-4.3: Add 4.2.16 through 4.2.19 (amd64)
  channels/stable-4.3.yaml
Labels: approved, lgtm

#148 channels/stable-4.2: Promote 4.1.38 to stable-4.2
  channels/stable-4.2.yaml
Labels: approved, lgtm

#149 hack/graph-util: Drop --token
  README.md
  hack/graph-util.py
Labels: approved, lgtm
