Repository openshift/cincinnati-graph-data, pull requests merged in 2021-04, with the labels that each got.

#302 channels/*-4.3: Promote 4.2.28 and 4.2.29 to fast/stable regardless of arch
  channels/fast-4.3.yaml
  channels/stable-4.3.yaml
Labels: approved, lgtm, lifecycle/rotten

#697 channels/stable-4.7: Populate with 4.6.z from stable-4.6
  channels/stable-4.7.yaml
Labels: approved, lgtm

#739 blocked-edges/4.6.2[23]: Block all incoming edge on OVN
  blocked-edges/4.6.22.yaml
  blocked-edges/4.6.23.yaml
Labels: approved, lgtm

#740 Partially revert "build-suggestions/4.7: Raise *_min to 4.y.9999"
  build-suggestions/4.7.yaml
Labels: approved, lgtm

#741 hack/test_errata: Test synopsis matching
  hack/test_errata.py
Labels: approved, lgtm

#750 graph-data.rs: update Cincinnati config
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
Labels: approved, lgtm

#752 Cargo: bump Cincinnati
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
  graph-data.rs/src/main.rs
Labels: approved, lgtm

#760 Revert "Cargo: bump Cincinnati"
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
  graph-data.rs/src/main.rs
Labels: approved, lgtm

#748 errata-webhook: add additional unit tests, refactor, and a fix
  hack/errata.py
  hack/test_errata.py
Labels: approved, lgtm

#761 channels/candidate-4.8: Backfill with 4.7.z
  channels/candidate-4.8.yaml
Labels: approved, lgtm

#772 Cargo: update dependencies
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
  graph-data.rs/src/main.rs
Labels: approved, lgtm

#775 Adding build suggestion for 4.8
  build-suggestions/4.8.yaml
Labels: approved, lgtm

#75 channels: Add 'feeder' and 'tombstones' properties
  README.md
  channels/candidate-4.2.yaml
  channels/candidate-4.3.yaml
  channels/candidate-4.4.yaml
  channels/candidate-4.5.yaml
  channels/candidate-4.6.yaml
  channels/candidate-4.7.yaml
  channels/eus-4.6.yaml
  channels/fast-4.2.yaml
  channels/fast-4.3.yaml
  channels/fast-4.4.yaml
  channels/fast-4.5.yaml
  channels/fast-4.6.yaml
  channels/fast-4.7.yaml
  channels/fast-4.8.yaml
  channels/prerelease-4.1.yaml
  channels/stable-4.1.yaml
  channels/stable-4.2.yaml
  channels/stable-4.3.yaml
  channels/stable-4.4.yaml
  channels/stable-4.5.yaml
  channels/stable-4.6.yaml
  channels/stable-4.7.yaml
  channels/stable-4.8.yaml
  hack/stabilization-changes.py
Labels: approved, lgtm, size/L

#784 channels/fast-4.8: Exclude 4.7.z releases
  channels/fast-4.8.yaml
Labels: approved, lgtm
