Repository openshift/cincinnati-graph-data, pull requests merged in 2023-08, with the labels that each got.

#3935 OTA-1004: build-suggestions/4.14: minor-min 4.13.7 for Kube-API removal ack
  build-suggestions/4.14.yaml
Labels: approved, lgtm, jira/valid-reference

#3944 Tombstone 4.13.7
  internal-channels/candidate.yaml
Labels: approved, lgtm

#3887 OTA-1000: RHSB2023-001: Add for 4.12.23+ -> 4.13 edges
  blocked-edges/4.13.0-RHSB2023001.yaml
  blocked-edges/4.13.1-RHSB2023001.yaml
  blocked-edges/4.13.2-RHSB2023001.yaml
  blocked-edges/4.13.3-RHSB2023001.yaml
  blocked-edges/4.13.4-RHSB2023001.yaml
  blocked-edges/4.13.5-RHSB2023001.yaml
  blocked-edges/4.13.6-RHSB2023001.yaml
Labels: approved, jira/valid-reference

#3970 blocked-edges/4.13.7-RHSB2023001: 4.13.8 has the final fixes
  blocked-edges/4.13.7-RHSB2023001.yaml
Labels: approved, lgtm

#3971 blocked-edges/4.13.6-RHSB2023001: Declare fixedIn 4.13.8 here too
  blocked-edges/4.13.6-RHSB2023001.yaml
Labels: approved, lgtm

#3983 `stable-4.13`: Add 4.12 ⟶ 4.13 edges
  blocked-edges/4.12.4-OVNCrashOnMigratedDualStack.yaml
  channels/stable-4.13.yaml
Labels: approved, lgtm

#3994 blocked-edges/4.13.*-PersistentVolumeDiskIDSymlinks: Convert to Always
  blocked-edges/4.13.0-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-ec.1-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-ec.2-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-ec.3-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-ec.4-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.0-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.2-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.3-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.4-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.5-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.6-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.7-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.0-rc.8-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.1-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.2-PersistentVolumeDiskIDSymlinks.yaml
  blocked-edges/4.13.3-PersistentVolumeDiskIDSymlinks.yaml
Labels: approved, lgtm

#4007 release-stable-minor.sh: QoL improvements
  hack/release-stable-minor.sh
Labels: approved, lgtm

#4030 blocked-edges/4.13.9-AWSMintModeWithoutCredentials: Fixed in 4.13.10
  blocked-edges/4.13.9-AWSMintModeWithoutCredentials.yaml
Labels: approved, lgtm
