Repository openshift/cincinnati-graph-data, pull requests merged in 2023-03, with the labels that each got.

#3237 *: Prepare for 4.14 development
  build-suggestions/4.14.yaml
  channels/candidate-4.14.yaml
Labels: approved, lgtm

#3243 OCPNODE-1502: Declare `LeakedMachineConfigBlocksMCO` on 4.11.26+ | 4.12.2+ | 4.13.0-ec.3+
  blocked-edges/4.11.26-leaked-machineconfig.yaml
  blocked-edges/4.11.27-leaked-machineconfig.yaml
  blocked-edges/4.11.28-leaked-machineconfig.yaml
  blocked-edges/4.11.29-leaked-machineconfig.yaml
  blocked-edges/4.11.30-leaked-machineconfig.yaml
  blocked-edges/4.11.31-leaked-machineconfig.yaml
  blocked-edges/4.12.2-leaked-machineconfig.yaml
  blocked-edges/4.12.3-leaked-machineconfig.yaml
  blocked-edges/4.12.4-leaked-machineconfig.yaml
  blocked-edges/4.12.5-leaked-machineconfig.yaml
  blocked-edges/4.12.6-leaked-machineconfig.yaml
  blocked-edges/4.12.7-leaked-machineconfig.yaml
  blocked-edges/4.13.0-ec.3-leaked-machineconfig.yaml
  blocked-edges/4.13.0-ec.4-leaked-machineconfig.yaml
Labels: approved, lgtm, jira/valid-reference

#3246 blocked-edges/4.11.31: Extend AWSOldBootImageLackAfterburn
  blocked-edges/4.11.31-AWSOldBootImageLackAfterburn.yaml
Labels: approved, lgtm

#3249 blocked-edges/4.12.*-leaked-machineconfig: Adjust 'to' for target patch
  blocked-edges/4.12.3-leaked-machineconfig.yaml
  blocked-edges/4.12.4-leaked-machineconfig.yaml
  blocked-edges/4.12.5-leaked-machineconfig.yaml
  blocked-edges/4.12.6-leaked-machineconfig.yaml
  blocked-edges/4.12.7-leaked-machineconfig.yaml
Labels: approved

#3250 validate-blocked-edges: match target version in content and filename
  hack/validate-blocked-edges.py
Labels: approved, lgtm

#3251 Remove unnecessary space in the message of conditional edge
  blocked-edges/4.13.0-ec.3-leaked-machineconfig.yaml
  blocked-edges/4.13.0-ec.4-leaked-machineconfig.yaml
Labels: approved, lgtm

#3266 Adding conditional update "PodmanMissingAuthFlag" for 4.11.* to 4.12.*
  blocked-edges/4.12.0-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.0-rc.8-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.1-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.2-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.3-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.4-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.5-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.6-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag.yaml
Labels: approved, lgtm

#3257 Updating the minor_min for 4.13 to 4.12.8
  build-suggestions/4.13.yaml
Labels: approved, lgtm

#3271 blocked-edges/4.12.7-leaked-machineconfig: Fixed in 4.12.8
  blocked-edges/4.12.7-leaked-machineconfig.yaml
Labels: approved, lgtm

#3273 blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag: 4.12.8 does not contain a fix
  blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag.yaml
Labels: approved, lgtm

#3280 blocked-edges/4.11.32-*: AWSOldBootImageLackAfterburn and LeakedMachineConfigBlocksMCO are unfixed
  blocked-edges/4.11.32-AWSOldBootImageLackAfterburn.yaml
  blocked-edges/4.11.32-leaked-machineconfig.yaml
Labels: approved, lgtm

#3292 blocked-edges/4.13.0-ec.4-leaked-machineconfig: Fixed in 4.13.0-rc.0
  blocked-edges/4.13.0-ec.4-leaked-machineconfig.yaml
Labels: approved, lgtm

#3300 AUTH-351: blocked-edges/4.13.0-*: Declare StrictPodSecurityViolation
  blocked-edges/4.13.0-ec.1-StrictPodSecurityViolation.yaml
  blocked-edges/4.13.0-ec.2-StrictPodSecurityViolation.yaml
  blocked-edges/4.13.0-ec.3-StrictPodSecurityViolation.yaml
  blocked-edges/4.13.0-ec.4-StrictPodSecurityViolation.yaml
  blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation.yaml
Labels: approved, lgtm, jira/valid-reference

#3304 blocked-edges/4.11.32-*: 4.11.33 fixes AWSOldBootImageLackAfterburn and LeakedMachineConfigBlocksMCO
  blocked-edges/4.11.32-AWSOldBootImageLackAfterburn.yaml
  blocked-edges/4.11.32-leaked-machineconfig.yaml
Labels: approved, lgtm

#3313 blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag: Fixed in 4.12.9
  blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag.yaml
Labels: approved, lgtm

#3322 Bump minimum for 4.13 upgrades to 4.12.9 for multiple bugs
  build-suggestions/4.13.yaml
Labels: approved, lgtm

#3326 blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag: Fixed in 4.12.9
  blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag.yaml
Labels: approved, lgtm

#3354 blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation: Fixed in 4.13.0-rc.2
  blocked-edges/4.13.0-rc.0-StrictPodSecurityViolation.yaml
Labels: approved, lgtm

#3357 blocked-edges: handle cluster_infrastructure_provider zero values
  blocked-edges/4.12.0-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.0-rc.8-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.1-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.2-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.3-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.4-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.5-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.6-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.7-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.12.8-OldBootImagesPodmanMissingAuthFlag.yaml
  blocked-edges/4.7.4-vsphere-hw-17-cross-node-networking.yaml
  blocked-edges/4.7.4-zz-vsphere-hostnames-changing.yaml
Labels: approved, lgtm
