Repository openshift/cincinnati-graph-data, pull requests merged in 2024-05, with the labels that each got.

#5200 Enable 4.14.24 in candidate channel
  internal-channels/candidate.yaml
Labels: approved, lgtm

#5205 Tombstone 4.15.1, 4.15.4
  internal-channels/candidate.yaml
Labels: approved, lgtm

#5204 COS-2781: `CephCapDropPanic` on 4.12.54+, 4.13.36+, 4.14.14+, 4.15.0+
  blocked-edges/4.12.54-CephCapDropPanic.yaml
  blocked-edges/4.12.55-CephCapDropPanic.yaml
  blocked-edges/4.12.56-CephCapDropPanic.yaml
  blocked-edges/4.13.36-CephCapDropPanic.yaml
  blocked-edges/4.13.37-CephCapDropPanic.yaml
  blocked-edges/4.13.38-CephCapDropPanic.yaml
  blocked-edges/4.13.39-CephCapDropPanic.yaml
  blocked-edges/4.13.40-CephCapDropPanic.yaml
  blocked-edges/4.13.41-CephCapDropPanic.yaml
  blocked-edges/4.14.14-CephCapDropPanic.yaml
  blocked-edges/4.14.15-CephCapDropPanic.yaml
  blocked-edges/4.14.16-CephCapDropPanic.yaml
  blocked-edges/4.14.17-CephCapDropPanic.yaml
  blocked-edges/4.14.18-CephCapDropPanic.yaml
  blocked-edges/4.14.19-CephCapDropPanic.yaml
  blocked-edges/4.14.20-CephCapDropPanic.yaml
  blocked-edges/4.14.21-CephCapDropPanic.yaml
  blocked-edges/4.14.22-CephCapDropPanic.yaml
  blocked-edges/4.14.23-CephCapDropPanic.yaml
  blocked-edges/4.14.24-CephCapDropPanic.yaml
  blocked-edges/4.15.0-CephCapDropPanic.yaml
  blocked-edges/4.15.10-CephCapDropPanic.yaml
  blocked-edges/4.15.11-CephCapDropPanic.yaml
  blocked-edges/4.15.12-CephCapDropPanic.yaml
  blocked-edges/4.15.2-CephCapDropPanic.yaml
  blocked-edges/4.15.3-CephCapDropPanic.yaml
  blocked-edges/4.15.5-CephCapDropPanic.yaml
  blocked-edges/4.15.6-CephCapDropPanic.yaml
  blocked-edges/4.15.7-CephCapDropPanic.yaml
  blocked-edges/4.15.8-CephCapDropPanic.yaml
  blocked-edges/4.15.9-CephCapDropPanic.yaml
Labels: approved, lgtm, jira/valid-reference

#5206 Add 4.13.41, 4.14.23, 4.15.11 to stable channel
  internal-channels/stable.yaml
Labels: approved, lgtm

#5218 `CRIAuthPluginRHEL`: Extend to 4.16.0-rc.0 but limit outgoing to <=4.15.11
  blocked-edges/4.16.0-ec.0-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-ec.1-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-ec.2-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-ec.3-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-ec.4-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-ec.5-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-ec.6-CRIAuthPluginRHEL.yaml
  blocked-edges/4.16.0-rc.0-CRIAuthPluginRHEL.yaml
Labels: approved, ¯\_(ツ)_/¯, lgtm

#5219 NE-1689: Declare `IngressDegradedOnRouterReloads` for <4.14.23
  blocked-edges/4.14.0-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.1-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.10-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.11-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.12-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.13-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.14-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.15-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.16-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.17-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.18-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.19-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.2-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.20-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.21-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.22-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.3-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.4-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.5-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.6-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.7-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.8-IngressDegradedOnRouterReloads.yaml
  blocked-edges/4.14.9-IngressDegradedOnRouterReloads.yaml
Labels: approved, lgtm, jira/valid-reference

#5221 Declare `ReconciledPlatformSCC` for 4.13.{17,18} -> 4.14.0
  blocked-edges/4.14.0-ReconciledPlatformSCC.yaml
Labels: approved, lgtm

#5222 Backfill 4.14.0 risks from 4.14.1 and remove 4.14.0 drop
  blocked-edges/4.14.0-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-AzureDefaultVMType.yaml
  blocked-edges/4.14.0-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ConsoleImplicitlyEnabled.yaml
  blocked-edges/4.14.0.yaml
Labels: approved, lgtm

#5226 AUTH-517: Declare `ServiceAccountsOAuth` for cluster with disabled registry
  blocked-edges/4.15.0-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.10-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.11-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.12-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.2-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.3-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.5-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.6-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.7-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.8-ServiceAccountsOAuth.yaml
  blocked-edges/4.15.9-ServiceAccountsOAuth.yaml
Labels: approved, lgtm, jira/valid-reference

#5231 CephCapDropPanic fixedIn 4.14.25 and 4.15.13
  blocked-edges/4.14.24-CephCapDropPanic.yaml
  blocked-edges/4.15.12-CephCapDropPanic.yaml
Labels: approved, lgtm

#5232 Extend ServiceAccountsOAuth to 4.15.13
  blocked-edges/4.15.13-ServiceAccountsOAuth.yaml
Labels: approved, lgtm

#5237 CephCapDropPanic fixed in 4.12.57
  blocked-edges/4.12.56-CephCapDropPanic.yaml
Labels: approved, lgtm

#5242 OCPCLOUD-2582: blocked-edges/4.16.0-rc.0-CRIAuthPluginRHEL: Fixed in rc.1
  blocked-edges/4.16.0-rc.0-CRIAuthPluginRHEL.yaml
Labels: approved, lgtm, jira/valid-reference

#5265 blocked-edges/4.13.41-CephCapDropPanic: Fixed in 4.13.42
  blocked-edges/4.13.41-CephCapDropPanic.yaml
Labels: approved, lgtm

#5268 AUTH-517: blocked-edges/4.15.14-ServiceAccountsOAuth: Not fixed
  blocked-edges/4.15.14-ServiceAccountsOAuth.yaml
Labels: approved, lgtm, jira/valid-reference

#5293 AUTH-517: blocked-edges/4.15.14-ServiceAccountsOAuth: Fixed in 4.15.15
  blocked-edges/4.15.14-ServiceAccountsOAuth.yaml
Labels: approved, lgtm, jira/valid-reference

#5289 OTA-1179: README: Clarify managed-cluster risk scoping
  README.md
Labels: approved, lgtm, jira/valid-reference

#5334 SDN-4871: blocked-edges/4.14.*-OVNInterConnectTransitionIPsec: Declare risk
  blocked-edges/4.14.0-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-ec.0-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-ec.1-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-ec.2-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-ec.3-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-ec.4-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.0-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.1-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.2-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.3-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.4-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.5-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.6-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.0-rc.7-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.1-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.10-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.11-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.12-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.13-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.14-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.15-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.16-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.17-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.18-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.19-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.2-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.20-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.21-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.22-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.23-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.24-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.25-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.26-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.27-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.28-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.3-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.4-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.5-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.6-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.7-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.8-OVNInterConnectTransitionIPsec.yaml
  blocked-edges/4.14.9-OVNInterConnectTransitionIPsec.yaml
Labels: approved, lgtm, jira/valid-reference
