Repository openshift/cincinnati-graph-data, pull requests merged in 2024-01, with the labels that each got.

#4570 Carry AROBrokenDNSMasq, OVNKubeMasteRDSPrsetop, and AzureDefaultVMType
  blocked-edges/4.13.28-AROBrokenDNSMasq.yaml
  blocked-edges/4.13.28-OVNKubeMasterDSPrestop.yaml
  blocked-edges/4.14.8-AROBrokenDNSMasq.yaml
  blocked-edges/4.14.8-AzureDefaultVMType.yaml
Labels: approved, lgtm

#4575 OCPCLOUD-2434: blocked-edges/4.14*: Declare AWSECRLegacyCredProvider
  blocked-edges/4.14.0-ec.0-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.1-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.2-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.3-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.4-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.0-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.1-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.2-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.3-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.4-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.5-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.6-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.7-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0.yaml
  blocked-edges/4.14.1-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.2-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.3-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.4-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.5-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.6-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.7-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.8-AWSECRLegacyCredProvider.yaml
Labels: approved, lgtm, jira/valid-reference

#4578 blocked-edges/4.15.0-rc.0: Declare EarlyAPICertRotation
  blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml
Labels: approved, lgtm

#4580 OCPCLOUD-2434: EWSECRLegacyCredProvider: Detect actual ECR usage from pullspecs
  blocked-edges/4.14.0-ec.0-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.1-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.2-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.3-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-ec.4-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.0-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.1-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.2-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.3-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.4-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.5-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.6-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.0-rc.7-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.1-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.2-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.3-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.4-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.5-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.6-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.7-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.8-AWSECRLegacyCredProvider.yaml
Labels: approved, lgtm, jira/valid-reference

#4581 ETCD-511: Set up EtcdBackupMountPointStuck for 4.14.[3-8]->5.15.0 RC0+ edges
  blocked-edges/4.15.0-rc.0-EtcdBackupMountPointStuck.yaml
  blocked-edges/4.15.0-rc.1-EtcdBackupMountPointStuck.yaml
Labels: approved, lgtm, jira/valid-reference

#4603 Carry `AROBrokenDNSMasq` and `OVNKubeMasterDSPrestop`
  blocked-edges/4.12.47-OVNKubeMasterDSPrestop.yaml
  blocked-edges/4.13.29-AROBrokenDNSMasq.yaml
  blocked-edges/4.13.29-OVNKubeMasterDSPrestop.yaml
Labels: approved, lgtm

#4609 Carry `AROBrokenDNSMasq`, `AWSECRLegacyCredProvider` and `AzureDefaultVMType` to 4.14.9
  blocked-edges/4.14.9-AROBrokenDNSMasq.yaml
  blocked-edges/4.14.9-AWSECRLegacyCredProvider.yaml
  blocked-edges/4.14.9-AzureDefaultVMType.yaml
Labels: approved, lgtm

#4613 EtcdBackupMountPointStuck: extend to 4.15.0-rc.2
  blocked-edges/4.15.0-rc.2-EtcdBackupMountPointStuck.yaml
Labels: approved, lgtm

#4615 Bump 4.15 min minor version to 4.14.9 for EtcdBackupMountPointStuck
  build-suggestions/4.15.yaml
Labels: approved, lgtm

#4616 4.14: Promote minor upgrades to stable and EUS channels
  channels/eus-4.14.yaml
  channels/stable-4.14.yaml
Labels: approved, lgtm

#4633 *: Prepare for 4.16 development
  build-suggestions/4.16.yaml
  channels/candidate-4.16.yaml
Labels: approved, lgtm

#4637 blocked-edges/4.13.29-AROBrokenDNSMasq: Fixed in 4.13.30
  blocked-edges/4.13.29-AROBrokenDNSMasq.yaml
Labels: approved, lgtm

#4639 blocked-edges/4.13.29-OVNKubeMasterDSPrestop: Fixed in 4.13.30
  blocked-edges/4.13.29-OVNKubeMasterDSPrestop.yaml
Labels: approved, lgtm

#4640 blocked-edges/4.14.9-AzureDefaultVMType: Fixed in 4.14.10
  blocked-edges/4.14.9-AzureDefaultVMType.yaml
Labels: approved

#4641 blocked-edges/4.14.10-AWSECRLegacyCredProvider: Still exposed
  blocked-edges/4.14.10-AWSECRLegacyCredProvider.yaml
Labels: approved

#4638 blocked-edges/4.14.9-AROBrokenDNSMasq: Fixed in 4.14.10
  blocked-edges/4.14.9-AROBrokenDNSMasq.yaml
Labels: approved, lgtm

#4646 blocked-edges/4.15.0-*-EtcdBackupMountPointStuck: Drop . from 'from' regexp
  blocked-edges/4.15.0-rc.0-EtcdBackupMountPointStuck.yaml
  blocked-edges/4.15.0-rc.1-EtcdBackupMountPointStuck.yaml
  blocked-edges/4.15.0-rc.2-EtcdBackupMountPointStuck.yaml
Labels: approved, lgtm

#4651 EtcdBackupMountPointStuck fixed in 4.15.0-rc.3
  blocked-edges/4.15.0-rc.2-EtcdBackupMountPointStuck.yaml
Labels: approved, lgtm

#4677 CCO-522: blocked-edges/4.15.0-rc.0-GCPMintModeRoleAdmin: Declare risk
  blocked-edges/4.15.0-ec.0-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-ec.1-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-ec.2-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-ec.3-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-rc.0-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-rc.1-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-rc.2-GCPMintModeRoleAdmin.yaml
  blocked-edges/4.15.0-rc.3-GCPMintModeRoleAdmin.yaml
Labels: approved, lgtm, jira/valid-reference

#4683 `OVNKubeMasterDSPrestop`: Fixed in 4.12.48
  blocked-edges/4.12.47-OVNKubeMasterDSPrestop.yaml
Labels: approved, lgtm

#4688 `GCPMintModeRoleAdmin`: Extend to 4.15.0-rc.4
  blocked-edges/4.15.0-rc.4-GCPMintModeRoleAdmin.yaml
Labels: approved
