Repository openshift/cincinnati-graph-data, pull requests merged in 2024-06, with the labels that each got.

#5352 OCPBUGS-33984: build-suggestions/4.16: Set minor_min to 4.15.17
  build-suggestions/4.16.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#5357 SDN-4871: blocked-edges/4.14.29-OVNInterConnectTransitionIPsec: Not fixed yet
  blocked-edges/4.14.29-OVNInterConnectTransitionIPsec.yaml
Labels: approved, lgtm, jira/valid-reference

#5360 Add the 4.17 build suggestions
  build-suggestions/4.17.yaml
Labels: lgtm

#5370 OTA-1297: blocked-edges: Declare TechPreviewSignatureStoresInDefault for 4.16.0-rc.3 and later
  blocked-edges/4.16.0-rc.3-TechPreviewSignatureStoresInDefault.yaml
  blocked-edges/4.16.0-rc.4-TechPreviewSignatureStoresInDefault.yaml
Labels: approved, lgtm, jira/valid-reference

#5376 OTA-1297: blocked-edges/4.17.0-ec.0-TechPreviewSignatureStoresInDefault: Not fixed yet
  blocked-edges/4.17.0-ec.0-TechPreviewSignatureStoresInDefault.yaml
Labels: approved, lgtm, jira/valid-reference

#5377 API-1813: blocked-edges/4.16.*-FlowControlV1Beta3Migration: Declare new risk
  blocked-edges/4.16.0-ec.0-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-ec.1-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-ec.2-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-ec.3-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-ec.4-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-ec.5-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-ec.6-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-rc.0-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-rc.1-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-rc.2-FlowControlV1Beta3Migration.yaml
  blocked-edges/4.16.0-rc.3-FlowControlV1Beta3Migration.yaml
Labels: approved, lgtm, jira/valid-reference

#5390 Block 4.14 due to bad boot order
  blocked-edges/4.14.0-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.1-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.10-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.11-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.12-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.13-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.14-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.15-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.16-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.17-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.18-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.19-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.2-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.20-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.21-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.22-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.23-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.24-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.25-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.26-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.27-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.28-ARODNSWrongBootSequence.yaml.yaml
  blocked-edges/4.14.29-ARODNSWrongBootSequence.yaml.yaml
  blocked-edges/4.14.3-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.4-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.5-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.6-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.7-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.8-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.9-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm

#5391 README: Fix "sentance" -> "sentence" typo
  README.md
Labels: approved, lgtm

#5398 OSASINFRA-3500: blocked-edges: Declare OpenStackAvailabilityZoneOutOfRange
  blocked-edges/4.14.29-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.14.30-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.15.15-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.15.16-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.15.17-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.15.18-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.16.0-ec.6-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.16.0-rc.0-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.16.0-rc.1-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.16.0-rc.2-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.16.0-rc.3-OpenStackAvailabilityZoneOutOfRange.yaml
  blocked-edges/4.16.0-rc.4-OpenStackAvailabilityZoneOutOfRange.yaml
Labels: approved, lgtm, jira/valid-reference

#5399 SDN-4871: blocked-edges/4.14.30-OVNInterConnectTransitionIPsec: Not fixed yet
  blocked-edges/4.14.30-OVNInterConnectTransitionIPsec.yaml
Labels: approved, lgtm, jira/valid-reference

#5402 build-suggestions/4.16: Set minor_min to 4.15.18
  build-suggestions/4.16.yaml
Labels: approved, lgtm

#5406 `OpenStackAvailabilityZoneOutOfRange`: Fixed in 4.16.0-rc.5
  blocked-edges/4.16.0-rc.4-OpenStackAvailabilityZoneOutOfRange.yaml
Labels: approved, lgtm

#5407 `TechPreviewSignatureStoresInDefault`: Fixed in 4.16.0-rc.5
  blocked-edges/4.16.0-rc.4-TechPreviewSignatureStoresInDefault.yaml
Labels: approved, lgtm

#5418 README: Explain scoping vs. OCP policy and support
  README.md
Labels: approved, lgtm

#5442 SDN-5055: Set up `OVNMulticastPacketLoss` for 4.16
  blocked-edges/4.16.0-rc.0-OVNMulticastPacketLoss.yaml
  blocked-edges/4.16.0-rc.1-OVNMulticastPacketLoss.yaml
  blocked-edges/4.16.0-rc.2-OVNMulticastPacketLoss.yaml
  blocked-edges/4.16.0-rc.3-OVNMulticastPacketLoss.yaml
  blocked-edges/4.16.0-rc.4-OVNMulticastPacketLoss.yaml
  blocked-edges/4.16.0-rc.5-OVNMulticastPacketLoss.yaml
  blocked-edges/4.16.0-rc.6-OVNMulticastPacketLoss.yaml
Labels: approved, lgtm, jira/valid-reference

#5447 blocked-edges/4.14.31-ARODNSWrongBootSequence: Not fixed yet
  blocked-edges/4.14.31-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm

#5448 SDN-4871: blocked-edges/4.14.31-OVNInterConnectTransitionIPsec: Not fixed yet
  blocked-edges/4.14.31-OVNInterConnectTransitionIPsec.yaml
Labels: approved, lgtm, jira/valid-reference

#5452 blocked-edges/4.15.18-OpenStackAvailabilityZoneOutOfRange: Fixed in 4.15.19
  blocked-edges/4.15.18-OpenStackAvailabilityZoneOutOfRange.yaml
Labels: approved, lgtm

#5459 Bump o/cincinnati to dc2abd15 to fix e2e tests
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
Labels: approved

#5461 Add 4.16.0-rc.9 to candidate-4.16
  channels/candidate-4.16.yaml
Labels: approved, lgtm

#5477 Bump cincinnati to 67fe062 to follow production
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
  graph-data.rs/src/check_releases.rs
Labels: approved, lgtm

#5490 GA 4.16
  blocked-edges/4.16.0-ec.0-PreRelease.yaml
  blocked-edges/4.16.0-ec.1-PreRelease.yaml
  blocked-edges/4.16.0-ec.2-PreRelease.yaml
  blocked-edges/4.16.0-ec.3-PreRelease.yaml
  blocked-edges/4.16.0-ec.4-PreRelease.yaml
  blocked-edges/4.16.0-ec.5-PreRelease.yaml
  blocked-edges/4.16.0-ec.6-PreRelease.yaml
  blocked-edges/4.16.0-rc.0-PreRelease.yaml
  blocked-edges/4.16.0-rc.1-PreRelease.yaml
  blocked-edges/4.16.0-rc.2-PreRelease.yaml
  blocked-edges/4.16.0-rc.3-PreRelease.yaml
  blocked-edges/4.16.0-rc.4-PreRelease.yaml
  blocked-edges/4.16.0-rc.5-PreRelease.yaml
  blocked-edges/4.16.0-rc.6-PreRelease.yaml
  blocked-edges/4.16.0-rc.9-PreRelease.yaml
  build-suggestions/4.16.yaml
  build-suggestions/4.17.yaml
  channels/eus-4.16.yaml
  channels/fast-4.16.yaml
  channels/stable-4.16.yaml
  internal-channels/fast.yaml
  internal-channels/stable.yaml
Labels: approved, lgtm
