Repository openshift/cincinnati-graph-data, pull requests merged in 2024-02, with the labels that each got.

#4705 show-edges.py: use raw strings for regexes
  hack/show-edges.py
Labels: approved, lgtm

#4713 blocked-edges/4.14.10-AWSECRLegacyCredProvider: fixedIn 4.14.11
  blocked-edges/4.14.10-AWSECRLegacyCredProvider.yaml
Labels: approved, lgtm

#4720 blocked-edges/4.15.0-rc.5-GCPMintModeRoleAdmin: Not fixed yet
  blocked-edges/4.15.0-rc.5-GCPMintModeRoleAdmin.yaml
Labels: approved, lgtm

#4725 IR-461: blocked-edges/4.14.*: Declare ARORegistryImagePreservation
  blocked-edges/4.14.0-ec.0-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.1-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.2-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.3-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.4-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.0-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.1-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.2-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.3-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.4-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.5-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.6-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.7-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.1-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.10-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.11-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.2-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.3-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.4-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.5-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.6-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.7-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.8-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.9-ARORegistryImagePreservation.yaml
Labels: approved, lgtm, jira/valid-reference

#4728 IR-461: blocked-edges/4.14.*: Pivot ARORegistryImagePreservation to AzureRegistryImagePreservation
  blocked-edges/4.14.0-ec.0-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.0-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.1-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.1-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.2-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.2-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.3-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.3-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.4-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.4-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.0-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.0-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.1-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.1-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.2-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.2-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.3-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.3-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.4-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.4-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.5-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.5-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.6-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.6-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.7-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.7-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.1-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.1-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.10-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.10-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.11-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.11-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.2-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.2-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.3-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.3-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.4-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.4-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.5-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.5-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.6-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.6-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.7-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.7-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.8-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.8-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.9-ARORegistryImagePreservation.yaml
  blocked-edges/4.14.9-AzureRegistryImagePreservation.yaml
Labels: approved, lgtm, jira/valid-reference

#4744 SDN-4481: Set up `NetPolicyTimeoutsHostNetworkedPodTraffic`
  blocked-edges/4.12.48-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.30-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.31-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.32-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.10-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.11-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.12-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.9-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.1-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.2-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.3-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.4-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.5-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Labels: do-not-merge/hold, approved, lgtm, jira/valid-reference

#4754 blocked-edges/4.14.12-AzureRegistryImagePreservation: Not yet fixed
  blocked-edges/4.14.12-AzureRegistryImagePreservation.yaml
Labels: approved, lgtm

#4759 `NetPolicyTimeoutsHostNetworkedPodTraffic`: Extend to 4.13.33
  blocked-edges/4.13.33-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Labels: approved, lgtm

#4762 `NetPolicyTimeoutsHostNetworkedPodTraffic`: Exclude cloud platforms from exposure
  blocked-edges/4.12.48-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.30-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.31-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.32-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.13.33-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.10-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.11-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.12-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.9-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.1-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.2-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.3-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.4-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.5-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Labels: approved, lgtm

#4763 IR-461: blocked-edges/4.14.*-AzureRegistryImagePreservation: Look for active registry use
  blocked-edges/4.14.0-ec.0-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.1-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.2-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.3-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-ec.4-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.0-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.1-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.2-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.3-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.4-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.5-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.6-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.0-rc.7-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.1-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.10-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.11-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.12-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.2-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.3-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.4-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.5-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.6-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.7-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.8-AzureRegistryImagePreservation.yaml
  blocked-edges/4.14.9-AzureRegistryImagePreservation.yaml
Labels: approved, lgtm, jira/valid-reference

#4766 Risk NetPolicyTimeoutsHostNetworkedPodTraffic does not impact 4.14+
  blocked-edges/4.14.10-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.11-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.12-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.14.9-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.1-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.2-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.3-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.4-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
  blocked-edges/4.15.0-rc.5-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Labels: approved, lgtm

#4780 Adding update risks for OCPBUGS-27261
  blocked-edges/4.14.0-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-ec.0-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-ec.1-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-ec.2-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-ec.3-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-ec.4-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.0-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.1-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.2-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.3-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.4-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.5-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.6-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.0-rc.7-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.1-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.10-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.2-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.3-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.4-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.5-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.6-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.7-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.8-AWSCustomDomainNodesNotReady.yaml
  blocked-edges/4.14.9-AWSCustomDomainNodesNotReady.yaml
Labels: approved, lgtm

#4796 Extending AzureRegistryImagePreservation
  blocked-edges/4.14.13-AzureRegistryImagePreservation.yaml
Labels: approved, lgtm

#4797 blocked-edges/4.14.10-AWSCustomDomainNodesNotReady: Explicit fixedIn: 4.14.11
  blocked-edges/4.14.10-AWSCustomDomainNodesNotReady.yaml
Labels: approved, lgtm

#4795 Extending NetPolicyTimeoutsHostNetworkedPodTraffic
  blocked-edges/4.13.33-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Labels: approved, lgtm

#4803 blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic: Fixed in 4.12.50
  blocked-edges/4.12.49-NetPolicyTimeoutsHostNetworkedPodTraffic.yaml
Labels: approved, lgtm

#4827 *: 4.14.14 guards against GCPMintModeRoleAdmin
  blocked-edges/4.15.0-rc.8-GCPMintModeRoleAdmin.yaml
  build-suggestions/4.15.yaml
Labels: approved, lgtm

#4831 blocked-edges/4.14.13-AzureRegistryImagePreservation: Not fixed in 4.14.14
  blocked-edges/4.14.14-AzureRegistryImagePreservation.yaml
Labels: approved, lgtm

#4840 GCPMintModeRoleAdmin fixed in 4.15.0
  blocked-edges/4.15.0-rc.8-GCPMintModeRoleAdmin.yaml
Labels: approved, lgtm

#4863 blocked-edges/4.15.0-*-PreRelease: Declare prerelease risks and automate
  blocked-edges/4.15.0-ec.0-PreRelease.yaml
  blocked-edges/4.15.0-ec.1-PreRelease.yaml
  blocked-edges/4.15.0-ec.2-PreRelease.yaml
  blocked-edges/4.15.0-ec.3-PreRelease.yaml
  blocked-edges/4.15.0-rc.0-PreRelease.yaml
  blocked-edges/4.15.0-rc.1-PreRelease.yaml
  blocked-edges/4.15.0-rc.2-PreRelease.yaml
  blocked-edges/4.15.0-rc.3-PreRelease.yaml
  blocked-edges/4.15.0-rc.4-PreRelease.yaml
  blocked-edges/4.15.0-rc.5-PreRelease.yaml
  blocked-edges/4.15.0-rc.7-PreRelease.yaml
  blocked-edges/4.15.0-rc.8-PreRelease.yaml
  hack/release-ga.sh
Labels: approved, lgtm

#4864 modify EarlyAPICertRotation risk to include promql
  blocked-edges/4.15.0-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.0-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.1-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.2-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.3-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.4-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.5-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.7-EarlyAPICertRotation.yaml
  blocked-edges/4.15.0-rc.8-EarlyAPICertRotation.yaml
Labels: approved, lgtm
