Repository openshift/cincinnati-graph-data, pull requests merged in 2024-12, with the labels that each got.

#6268 OTA-1392: channels/stable-4.16: Add 4.14.z
  channels/candidate-4.14.yaml
  channels/candidate-4.16.yaml
  channels/fast-4.14.yaml
  channels/fast-4.16.yaml
  channels/stable-4.14.yaml
  channels/stable-4.16.yaml
  hack/release-stable-minor.sh
Labels: approved, lgtm, jira/valid-reference

#6361 OTA-1392: channels/candidate-4.*: 4.(y-2).0-* prereleases
  channels/candidate-4.14.yaml
  channels/candidate-4.16.yaml
Labels: approved, lgtm, jira/valid-reference

#6388 *: Prepare for 4.19 development
  build-suggestions/4.19.yaml
  channels/candidate-4.19.yaml
Labels: approved, lgtm

#6391 COS-1942: blocked-edges/4.12.0-rc.7-AWSOldBootImage: Fixed in 4.12.0-rc.8
  blocked-edges/4.12.0-rc.7-AWSOldBootImage.yaml
Labels: approved, lgtm, jira/valid-reference

#6399 SDN-5422: blocked-edges/4.15.40-OVNIPsecConnectivity: Not fixed yet
  blocked-edges/4.15.40-OVNIPsecConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#6331 add a known risk for 4.18.0-ec.3
  blocked-edges/4.18.0-ec.3-CMOSuddenStrictConfigValidation.yaml
  blocked-edges/4.18.0-ec.4-CMOSuddenStrictConfigValidation.yaml
  blocked-edges/4.18.0-rc.0-CMOSuddenStrictConfigValidation.yaml
Labels: approved, lgtm

#6402 `CMOSuddenStrictConfigValidation`: Fix regexes
  blocked-edges/4.18.0-ec.3-CMOSuddenStrictConfigValidation.yaml
  blocked-edges/4.18.0-ec.4-CMOSuddenStrictConfigValidation.yaml
  blocked-edges/4.18.0-rc.0-CMOSuddenStrictConfigValidation.yaml
Labels: approved, lgtm

#6360 OTA-1392: hack/release-*: Update scripts to add 4.(y-2).z to *-4.even channels
  hack/release-ga.sh
  hack/release-open.sh
  hack/release-stable-minor.sh
Labels: approved, lgtm, jira/valid-reference

#6403 SDN-5485: `OVNLocalnetWithNoSubnets`: ->4.17.[0-6] with virtualization
  blocked-edges/4.17.0-OVNLocalnetWithNoSubnets.yaml
  blocked-edges/4.17.1-OVNLocalnetWithNoSubnets.yaml
  blocked-edges/4.17.2-OVNLocalnetWithNoSubnets.yaml
  blocked-edges/4.17.3-OVNLocalnetWithNoSubnets.yaml
  blocked-edges/4.17.4-OVNLocalnetWithNoSubnets.yaml
  blocked-edges/4.17.5-OVNLocalnetWithNoSubnets.yaml
  blocked-edges/4.17.6-OVNLocalnetWithNoSubnets.yaml
Labels: approved, lgtm, jira/valid-reference

#6405 `CMOSuddenStrictConfigValidation`: Extend to 4.18 RC1, bump 4.18 `z_min` to EC3
  blocked-edges/4.18.0-rc.1-CMOSuddenStrictConfigValidation.yaml
  build-suggestions/4.18.yaml
Labels: approved, lgtm

#6409 SDN-5422: blocked-edges/4.15.41-OVNIPsecConnectivity: Not fixed yet
  blocked-edges/4.15.41-OVNIPsecConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#6412 OTA-1392: channels/candidate-4.18: Add 4.16.z
  channels/candidate-4.18.yaml
Labels: approved, lgtm, jira/valid-reference

#6413 blocked-edges/4.16.0-rc.9-PreRelease: Fixed in 4.16.0
  blocked-edges/4.16.0-rc.9-PreRelease.yaml
Labels: approved, lgtm

#6444 COS-3078: Declare `NUMAResourcesOperatorCrashLoopBackOff` risk
  blocked-edges/4.16.25-NUMAResourcesOperatorCrashLoopBackOff.yaml
  blocked-edges/4.16.26-NUMAResourcesOperatorCrashLoopBackOff.yaml
  blocked-edges/4.17.7-NUMAResourcesOperatorCrashLoopBackOff.yaml
  blocked-edges/4.17.8-NUMAResourcesOperatorCrashLoopBackOff.yaml
Labels: approved, lgtm, jira/valid-reference

#6449 NUMAResourcesOperatorCrashLoopBackOff fixed in 4.17.9
  blocked-edges/4.17.8-NUMAResourcesOperatorCrashLoopBackOff.yaml
Labels: approved, lgtm

#6460 NO-JIRA: blocked-edges/4.18.0-rc.1-CMOSuddenStrictConfigValidation.yaml: Set the risk as fixed in rc.2
  blocked-edges/4.18.0-rc.1-CMOSuddenStrictConfigValidation.yaml
Labels: approved, lgtm, jira/valid-reference

#6477 Add 4.13.54, 4.14.43, 4.15.40, 4.15.41, and 4.16.26 to stable channels
  channels/stable-4.13.yaml
  channels/stable-4.14.yaml
  channels/stable-4.15.yaml
  channels/stable-4.16.yaml
  internal-channels/stable.yaml
Labels: approved

#6491 COS-3068: Declare the `FCoEBootFromSANKernelDriverQedf` risk and mark it as fixed in 4.16.27 and 4.17.9
  blocked-edges/4.16.25-FCoEBootFromSANKernelDriverQedf.yaml
  blocked-edges/4.16.26-FCoEBootFromSANKernelDriverQedf.yaml
  blocked-edges/4.17.7-FCoEBootFromSANKernelDriverQedf.yaml
  blocked-edges/4.17.8-FCoEBootFromSANKernelDriverQedf.yaml
Labels: approved, lgtm, jira/valid-reference

#6493 Add 4.17.9 and 4.16.27 to stable channels
  channels/eus-4.16.yaml
  channels/stable-4.16.yaml
  channels/stable-4.17.yaml
  internal-channels/stable.yaml
Labels: approved, lgtm

#6502 SDN-5422: blocked-edges/4.15.42-OVNIPsecConnectivity: Not fixed yet
  blocked-edges/4.15.42-OVNIPsecConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#6506 MCO-1481: blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.3-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference
