Repository openshift/cincinnati-graph-data, pull requests merged in 2024-10, with the labels that each got.

#5903 `cargo update --manifest-path graph-data.rs/Cargo.toml`
  graph-data.rs/Cargo.lock
Labels: approved, lgtm

#6012 NO-JIRA: Release GA 4.17
  blocked-edges/4.17.0-ec.0-PreRelease.yaml
  blocked-edges/4.17.0-ec.1-PreRelease.yaml
  blocked-edges/4.17.0-ec.2-PreRelease.yaml
  blocked-edges/4.17.0-ec.3-PreRelease.yaml
  blocked-edges/4.17.0-rc.0-PreRelease.yaml
  blocked-edges/4.17.0-rc.1-PreRelease.yaml
  blocked-edges/4.17.0-rc.2-PreRelease.yaml
  blocked-edges/4.17.0-rc.3-PreRelease.yaml
  blocked-edges/4.17.0-rc.5-PreRelease.yaml
  blocked-edges/4.17.0-rc.6-PreRelease.yaml
  build-suggestions/4.17.yaml
  build-suggestions/4.18.yaml
  channels/fast-4.17.yaml
  channels/stable-4.17.yaml
  internal-channels/fast.yaml
  internal-channels/stable.yaml
Labels: ok-to-test, approved, lgtm, jira/valid-reference

#6044 NO-ISSUE: hack/stabilization-changes: Add support for autoExtend
  README.md
  blocked-edges/4.14.38-ARODNSWrongBootSequence.yaml
  hack/stabilization-changes.py
Labels: approved, lgtm, jira/valid-reference

#6077 blocked-edges/4.13.51-ARODNSWrongBootSequence: autoExtend on ARO-9234
  blocked-edges/4.13.51-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm

#6078 ARO-9234: blocked-edges/4.13.52-ARODNSWrongBootSequence: Auto-extend to 4.13.52
  blocked-edges/4.13.52-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm, jira/valid-reference

#6107 blocked-edges/4.14.39-ARODNSWrongBootSequence: Auto-extend to 4.14.39
  blocked-edges/4.14.39-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm

#6114 NO-JIRA: Add hongkailiu into cincinnati-graph-data-approvers
  OWNERS_ALIASES
Labels: approved, lgtm, jira/valid-reference

#6122 SDN-5422: Set up OVNIPsecConnectivity for 4.14 -> 4.15 paths
  blocked-edges/4.15.0-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.1-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.10-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.11-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.12-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.13-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.14-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.15-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.16-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.17-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.18-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.19-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.2-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.20-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.21-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.22-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.23-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.24-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.25-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.26-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.27-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.3-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.4-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.5-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.6-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.7-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.8-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.9-OVNIPsecConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#6138 Ocpbugs 35300 aro fixed
  blocked-edges/4.13.52-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.39-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm

#6137 SDN-5422: Set up OVNIPsecConnectivity for 4.14 -> 4.15 paths (more versions)
  blocked-edges/4.15.0-rc.0-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.1-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.2-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.3-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.4-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.5-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.7-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.0-rc.8-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.28-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.29-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.30-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.31-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.32-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.33-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.34-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.35-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.36-OVNIPsecConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#6139 Ocpbugs 35300 aro unblock
  blocked-edges/4.13.51-ARODNSWrongBootSequence.yaml
  blocked-edges/4.13.52-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.38-ARODNSWrongBootSequence.yaml
  blocked-edges/4.14.39-ARODNSWrongBootSequence.yaml
Labels: approved, lgtm

#6145 Extend `OVNIPsecConnectivity` risk to 4.15.37
  blocked-edges/4.15.37-OVNIPsecConnectivity.yaml
Labels: approved, lgtm

#6173 AUTH-550: Set up OAuthServerDownIfSpaceInIDPName for 4.16 -> 4.17 paths
  blocked-edges/4.17.0-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.0-rc.0-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.0-rc.1-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.0-rc.2-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.0-rc.3-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.0-rc.5-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.0-rc.6-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.1-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.2-OAuthServerDownIfSpaceInIDPName.yaml
  blocked-edges/4.17.3-OAuthServerDownIfSpaceInIDPName.yaml
Labels: approved, lgtm, jira/valid-reference
