Repository openshift/cincinnati-graph-data, pull requests merged in 2025-04, with the labels that each got.

#6997 CORENET-5832: Set up OVNWithMultipleClusterNetworks to block paths to 4.18
  blocked-edges/4.18.1-OVNWithMultipleClusterNetworks.yaml
  blocked-edges/4.18.2-OVNWithMultipleClusterNetworks.yaml
  blocked-edges/4.18.3-OVNWithMultipleClusterNetworks.yaml
  blocked-edges/4.18.4-OVNWithMultipleClusterNetworks.yaml
  blocked-edges/4.18.5-OVNWithMultipleClusterNetworks.yaml
  blocked-edges/4.18.6-OVNWithMultipleClusterNetworks.yaml
  blocked-edges/4.18.7-OVNWithMultipleClusterNetworks.yaml
Labels: approved, lgtm, jira/valid-reference

#7021 Revert "blocked-edges/4.11.31-*: 4.11.33 fixes `AWSOldBootImageLackAfterburn` and `LeakedMachineConfigBlocksMCO`"
  blocked-edges/4.11.31-AWSOldBootImageLackAfterburn.yaml
  blocked-edges/4.11.31-leaked-machineconfig.yaml
Labels: approved, lgtm

#7030 CORENET-5832: blocked-edges/4.18.8-OVNWithMultipleClusterNetworks: Not fixed yet
  blocked-edges/4.18.8-OVNWithMultipleClusterNetworks.yaml
Labels: approved, lgtm, jira/valid-reference

#7038 Make release-stable-minor.sh runnable on MacOS
  hack/release-stable-minor.sh
Labels: approved, lgtm

#7067 OVNWithMultipleClusterNetworks fixedIn 4.18.9
  blocked-edges/4.18.8-OVNWithMultipleClusterNetworks.yaml
Labels: approved, lgtm

#7079 CORENET-5630: blocked-edges/4.15.48-OVNIPsecPausedMCPConnectivity: Fixed in 4.15.49
  blocked-edges/4.15.48-OVNIPsecPausedMCPConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#7144 OCPBUGS-54594: ARM64 nodes to apply a bootloader update at 4.18.11 or later
  build-suggestions/4.19.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7020 MCO-1585: set up LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO to block affected upgrade paths
  blocked-edges/4.14.47-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.14.48-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.14.49-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.14.50-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.15.45-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.15.46-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.15.47-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.15.48-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.31-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.32-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.33-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.34-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.35-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.36-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.16.37-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.12-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.13-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.14-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.15-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.16-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.17-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.18-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.19-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.20-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.21-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.17.22-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.18.1-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.18.2-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.18.3-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.18.4-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.18.5-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
  blocked-edges/4.19.0-ec.1-LabeledMachineConfigAndContainerRuntimeConfigBlocksMCO.yaml
Labels: approved, lgtm, jira/valid-reference

#7174 CNF-17689: Set up `MetallbBgpBfdFrrRpm` for 4.18.{10,11}
  blocked-edges/4.18.10-MetallbBgpBfdFrrRpm.yaml
  blocked-edges/4.18.11-MetallbBgpBfdFrrRpm.yaml
Labels: approved, lgtm, jira/valid-reference
