Repository openshift/cincinnati-graph-data, pull requests merged in 2025-02, with the labels that each got.

#6702 MCO-1481: blocked-edges/4.18.0-rc.[78]-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.7-MachineConfigServerCARotation.yaml
  blocked-edges/4.18.0-rc.8-MachineConfigServerCARotation.yaml
Labels: approved, lgtm

#6727 MCO-1481: blocked-edges/4.18.0-rc.9-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.9-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference

#6759 MCO-1481: blocked-edges/4.18.0-rc.10-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.10-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference

#6804 MCO-1481: blocked-edges/4.18.1-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.1-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference

#6808 NO-JIRA: Release GA 4.18
  blocked-edges/4.18.0-ec.0-PreRelease.yaml
  blocked-edges/4.18.0-ec.1-PreRelease.yaml
  blocked-edges/4.18.0-ec.2-PreRelease.yaml
  blocked-edges/4.18.0-ec.3-PreRelease.yaml
  blocked-edges/4.18.0-ec.4-PreRelease.yaml
  blocked-edges/4.18.0-rc.0-PreRelease.yaml
  blocked-edges/4.18.0-rc.1-PreRelease.yaml
  blocked-edges/4.18.0-rc.10-PreRelease.yaml
  blocked-edges/4.18.0-rc.2-PreRelease.yaml
  blocked-edges/4.18.0-rc.3-PreRelease.yaml
  blocked-edges/4.18.0-rc.4-PreRelease.yaml
  blocked-edges/4.18.0-rc.5-PreRelease.yaml
  blocked-edges/4.18.0-rc.6-PreRelease.yaml
  blocked-edges/4.18.0-rc.7-PreRelease.yaml
  blocked-edges/4.18.0-rc.8-PreRelease.yaml
  blocked-edges/4.18.0-rc.9-PreRelease.yaml
  build-suggestions/4.18.yaml
  build-suggestions/4.19.yaml
  channels/eus-4.18.yaml
  channels/fast-4.18.yaml
  channels/stable-4.18.yaml
  internal-channels/stable.yaml
Labels: approved, lgtm, jira/valid-reference

#6830 OTA-1310: channels/stable-4.1[234]: Manually add 4.12.71
  channels/stable-4.12.yaml
  channels/stable-4.13.yaml
  channels/stable-4.14.yaml
Labels: approved, jira/valid-reference

#6837 OWNERS: Shift Lala to emeritus_approvers
  OWNERS
  OWNERS_ALIASES
Labels: approved, lgtm

#6846 MCO-1481: blocked-edges/4.18.1-MachineConfigServerCARotation: Declare as fixed in 4.18.2
  blocked-edges/4.18.1-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference

#6835 CNTRLPLANE-256: blocked-edges/4.17-HostedClusterIsProgressingStuckCondition: Declare risk
  blocked-edges/4.17.16-HostedClusterIsProgressingStuckCondition.yaml
  blocked-edges/4.17.17-HostedClusterIsProgressingStuckCondition.yaml
  blocked-edges/4.17.18-HostedClusterIsProgressingStuckCondition.yaml
  blocked-edges/4.17.19-HostedClusterIsProgressingStuckCondition.yaml
Labels: approved, lgtm, jira/valid-reference
