Repository openshift/cincinnati-graph-data, pull requests merged in 2025-01, with the labels that each got.

#6522 build-suggestions/4.18: Raise minor_min to 4.17.11
  build-suggestions/4.18.yaml
Labels: approved, lgtm

#6561 SDN-5422: blocked-edges/4.15.42-OVNIPsecConnectivity: Drop file, fixed in 4.15.42
  blocked-edges/4.15.41-OVNIPsecConnectivity.yaml
  blocked-edges/4.15.42-OVNIPsecConnectivity.yaml
Labels: approved, lgtm, jira/valid-reference

#6572 blocked-edges/4.18.0-rc.4-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.4-MachineConfigServerCARotation.yaml
Labels: approved, lgtm

#6584 OTA-1310: Remove stable channel 4.12.z feeders
  channels/stable-4.12.yaml
  channels/stable-4.13.yaml
  channels/stable-4.14.yaml
Labels: approved, lgtm, jira/valid-reference

#6601 MCO-1481: blocked-edges/4.18.0-rc.5-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.5-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference

#6610 Tombstone 4.17.13
  internal-channels/candidate.yaml
Labels: tide/merge-method-squash, approved, lgtm

#6632 MCO-1481: blocked-edges/4.18.0-rc.6-MachineConfigServerCARotation: Extend risk
  blocked-edges/4.18.0-rc.6-MachineConfigServerCARotation.yaml
Labels: approved, lgtm, jira/valid-reference
