Repository openshift/cincinnati-graph-data, pull requests merged in 2025-05, with the labels that each got.

#7193 OCPNODE-3074: Declare `CRIOLayerCompressionPulls` for 4.18.1..6
  blocked-edges/4.18.1-CRIOLayerCompressionPulls.yaml
  blocked-edges/4.18.2-CRIOLayerCompressionPulls.yaml
  blocked-edges/4.18.3-CRIOLayerCompressionPulls.yaml
  blocked-edges/4.18.4-CRIOLayerCompressionPulls.yaml
  blocked-edges/4.18.5-CRIOLayerCompressionPulls.yaml
  blocked-edges/4.18.6-CRIOLayerCompressionPulls.yaml
Labels: approved, lgtm, jira/valid-reference

#7229 OCPBUGS-55359: build-suggestions/4.19: Raise minor_min to 4.18.13
  build-suggestions/4.19.yaml
Labels: approved, lgtm, jira/valid-bug, jira/valid-reference

#7197 OCPNODE-3119: Declare `MCOContainerRuntimeConfigStaleFinalizer` for 4.17.11..24
  blocked-edges/4.17.11-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.12-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.13-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.14-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.15-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.16-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.17-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.18-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.19-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.20-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.21-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.22-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.23-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.24-MCOContainerRuntimeConfigStaleFinalizer.yaml
Labels: approved, lgtm, jira/valid-reference

#7237 OCPNODE-3119: Restrict `from:` on `MCOContainerRuntimeConfigStaleFinalizer`
  blocked-edges/4.17.11-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.12-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.13-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.14-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.15-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.16-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.17-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.18-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.19-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.20-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.21-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.22-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.23-MCOContainerRuntimeConfigStaleFinalizer.yaml
  blocked-edges/4.17.24-MCOContainerRuntimeConfigStaleFinalizer.yaml
Labels: approved, lgtm, jira/valid-reference

#7239 *: Prepare for 4.20 development
  build-suggestions/4.20.yaml
  channels/candidate-4.20.yaml
Labels: approved, lgtm

#7240 Use python3 shebang
  hack/validate-blocked-edges.py
Labels: approved, lgtm

#7228 OCPNODE-3245: Declare `KubeletStartFailingFromRestoreconTimeout` for 4.18.0..12
  blocked-edges/4.18.0-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.1-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.10-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.11-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.12-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.2-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.3-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.4-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.5-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.6-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.7-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.8-KubeletStartFailingFromRestoreconTimeout.yaml
  blocked-edges/4.18.9-KubeletStartFailingFromRestoreconTimeout.yaml
Labels: approved, lgtm, jira/valid-reference

#7244 NO-JIRA: update doc: add the Cincinnati Consumption section
  README.md
Labels: approved, lgtm, jira/valid-reference

#7292 Promote 4.16.40, 4.17.29, and 4.18.13 to stable channels
  channels/eus-4.16.yaml
  channels/eus-4.18.yaml
  channels/stable-4.16.yaml
  channels/stable-4.17.yaml
  channels/stable-4.18.yaml
  internal-channels/stable.yaml
Labels: approved, lgtm

#7227 OCPBUGS-55193: channels/stable-*: Remove 4.14.z feeders from stable channels
  channels/stable-4.14.yaml
  channels/stable-4.15.yaml
  channels/stable-4.16.yaml
Labels: approved, lgtm, jira/valid-bug, jira/severity-moderate, jira/valid-reference

#7301 OCPCLOUD-2975: Declare NonZonalAzureMachineSetScaling Risk
  blocked-edges/4.15.48-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.15.49-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.15.50-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.15.51-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.16.38-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.16.39-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.16.40-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.17-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.18-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.19-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.20-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.21-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.22-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.23-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.24-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.25-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.26-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.27-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.28-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.29-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.17.30-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.1-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.10-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.11-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.12-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.13-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.14-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.2-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.3-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.4-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.5-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.6-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.7-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.8-NonZonalAzureMachineSetScaling.yaml
  blocked-edges/4.18.9-NonZonalAzureMachineSetScaling.yaml
Labels: approved, lgtm, jira/valid-reference

#7245 NO-JIRA: Add docs for some directories
  Dockerfile
  README.md
  build-suggestions/README.md
  deploy/2-build-config.yaml
  graph-data.rs/.dockerignore
  graph-data.rs/Dockerfile
  graph-data.rs/README.md
  hack/README.md
  hack/exposure-length.sh
  hack/release-ga.sh
  internal-channels/README.md
Labels: approved, lgtm, jira/valid-reference

#7330 MCO-1702: Declare RHELFailedRebootMissingService Risk
  blocked-edges/4.16.38-RHELFailedRebootMissingService.yaml
  blocked-edges/4.16.39-RHELFailedRebootMissingService.yaml
  blocked-edges/4.16.40-RHELFailedRebootMissingService.yaml
  blocked-edges/4.16.41-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.22-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.23-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.24-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.25-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.26-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.27-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.28-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.29-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.30-RHELFailedRebootMissingService.yaml
  blocked-edges/4.17.31-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.10-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.11-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.12-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.13-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.14-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.15-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.6-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.7-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.8-RHELFailedRebootMissingService.yaml
  blocked-edges/4.18.9-RHELFailedRebootMissingService.yaml
Labels: approved, lgtm, jira/valid-reference

#6969 [OTA-1464]Bump cincinnati to 88bb8cb7
  graph-data.rs/Cargo.lock
  graph-data.rs/Cargo.toml
Labels: approved, lgtm

#7360 blocked-edges/4.15.51-NonZonalAzureMachineSetScaling: Fixed in 4.15.52
  blocked-edges/4.15.51-NonZonalAzureMachineSetScaling.yaml
Labels: approved, lgtm
